Set-Content -Encoding UTF8 -Path C:\github\dbatools\allcommands.ps1 -Value "### DO NOT EDIT THIS FILE DIRECTLY ###"
Get-ChildItem -Path "C:\github\dbatools\functions\*.ps1" -Recurse | Get-Content | Add-Content C:\github\dbatools\allcommands.ps1
Get-ChildItem -Path "C:\github\dbatools\internal\functions\*.ps1" -Recurse | Get-Content | Add-Content C:\github\dbatools\allcommands.ps1

Remove-Item -Recurse C:\gallery -Force
mkdir C:\gallery\dbatools
robocopy c:\github\dbatools C:\gallery\dbatools /S /XF *.psproj* *.git* *.yml /XD .git .github Tests .vscode | Out-String | Out-Null

Remove-Item -Recurse C:\gallery\dbatools\bin\build -ErrorAction Ignore
Remove-Item -Recurse C:\gallery\dbatools\bin\projects -ErrorAction Ignore
Remove-Item -Recurse C:\gallery\dbatools\bin\StructuredLogger.dll -ErrorAction Ignore

Publish-Module -Path c:\gallery\dbatools -NuGetApiKey xyz