Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

choco install chocolatey -y
choco install sql-server-management-studio -y
choco install azure-data-studio -y
choco install azuredatastudio-powershell -y
choco install git.install -y
choco install vscode -y
choco install vscode-powershell -y
choco install powerbi -y
choco install daxstudio -y
choco install tabular-editor -y
choco install sqlsearch -Y
choco install sqlsentryplanexplorer -y
choco install docker-desktop -y
choco install visualstudio2017sql -Y
choco install github-desktop -y
choco install python3 -y
choco install snagit -y
choco install camtasia -y
choco install greenshot -y
choco install gitkraken 
choco install googlechrome -y
choco install sysinternals -y
choco install sublimetext3 -y
choco install sublimemerge -y
choco install sql-server-express -y
choco install sqltoolbelt -Y
choco install microsoft-teams -y
choco install slack -y
choco install minikube -y
choco install kubernetes-helm -y
choco install kubernetes-cli -y
choco install microsoftazurestorageexplorer -y
choco install putty.install -y
choco install nodejs.install -y
choco install r.project -y
choco install r.studio -y
choco install autohotkey.portable -y
choco install markdownmonster -y
choco install paint.net -y
choco install notepadplusplus.install -y
choco install vcredist140 -y
choco install nuget.commandline -y
choco install filezilla -y
choco install curl -y
choco install cpu-z -y
choco install treesizefree -y
choco install azure-cli -y
choco install poshgit -y
choco install git-credential-manager-for-windows -y
choco install rdcman -y

choco install adblockpluschrome -y
choco install docker-compose -y
choco install spotify -y
choco install office365proplus -y
choco install pester -y
choco install docker-cli -y

choco install lastpass -y
choco install telegram.install -y
choco install whatsapp -y
choco install jenkins -y
