PS C:\Windows\system32> Get-Command

CommandType     Name                                               ModuleName
-----------     ----                                               ----------
Alias           Add-ProvisionedAppxPackage                         Dism
Alias           Apply-WindowsUnattend                              Dism
Alias           Flush-Volume                                       Storage
Alias           Get-PhysicalDiskSNV                                Storage
Alias           Get-ProvisionedAppxPackage                         Dism
Alias           Initialize-Volume                                  Storage
Alias           Move-SmbClient                                     SmbWitness
Alias           Remove-ProvisionedAppxPackage                      Dism
Alias           Write-FileSystemCache                              Storage
Function        A:
Function        Add-BCDataCacheExtension                           BranchCache
Function        Add-BitLockerKeyProtector                          BitLocker
Function        Add-DnsClientNrptRule                              DnsClient
Function        Add-DtcClusterTMMapping                            MsDtc
Function        Add-InitiatorIdToMaskingSet                        Storage
Function        Add-MpPreference                                   Defender
Function        Add-NetEventNetworkAdapter                         NetEventPacketCapture
Function        Add-NetEventPacketCaptureProvider                  NetEventPacketCapture
Function        Add-NetEventProvider                               NetEventPacketCapture
Function        Add-NetEventVmNetworkAdapter                       NetEventPacketCapture
Function        Add-NetEventVmSwitch                               NetEventPacketCapture
Function        Add-NetIPHttpsCertBinding                          NetworkTransition
Function        Add-NetLbfoTeamMember                              NetLbfo
Function        Add-NetLbfoTeamNic                                 NetLbfo
Function        Add-NetNatExternalAddress                          NetNat
Function        Add-NetNatStaticMapping                            NetNat
Function        Add-NetSwitchTeamMember                            NetSwitchTeam
Function        Add-OdbcDsn                                        Wdac
Function        Add-PartitionAccessPath                            Storage
Function        Add-PhysicalDisk                                   Storage
Function        Add-Printer                                        PrintManagement
Function        Add-PrinterDriver                                  PrintManagement
Function        Add-PrinterPort                                    PrintManagement
Function        Add-TargetPortToMaskingSet                         Storage
Function        Add-VirtualDiskToMaskingSet                        Storage
Function        Add-VpnConnection                                  VpnClient
Function        Add-VpnConnectionRoute                             VpnClient
Function        Add-VpnConnectionTriggerApplication                VpnClient
Function        Add-VpnConnectionTriggerDnsConfiguration           VpnClient
Function        Add-VpnConnectionTriggerTrustedNetwork             VpnClient
Function        B:
Function        Backup-BitLockerKeyProtector                       BitLocker
Function        Block-SmbShareAccess                               SmbShare
Function        C:
Function        cd..
Function        cd\
Function        Clear-AssignedAccess                               AssignedAccess
Function        Clear-BCCache                                      BranchCache
Function        Clear-BitLockerAutoUnlock                          BitLocker
Function        Clear-Disk                                         Storage
Function        Clear-DnsClientCache                               DnsClient
Function        Clear-FileStorageTier                              Storage
Function        Clear-Host
Function        Clear-StorageDiagnosticInfo                        Storage
Function        Close-SmbOpenFile                                  SmbShare
Function        Close-SmbSession                                   SmbShare
Function        Configuration                                      PSDesiredStateConfiguration
Function        Connect-IscsiTarget                                iSCSI
Function        Connect-VirtualDisk                                Storage
Function        Copy-NetFirewallRule                               NetSecurity
Function        Copy-NetIPsecMainModeCryptoSet                     NetSecurity
Function        Copy-NetIPsecMainModeRule                          NetSecurity
Function        Copy-NetIPsecPhase1AuthSet                         NetSecurity
Function        Copy-NetIPsecPhase2AuthSet                         NetSecurity
Function        Copy-NetIPsecQuickModeCryptoSet                    NetSecurity
Function        Copy-NetIPsecRule                                  NetSecurity
Function        D:
Function        Debug-MMAppPrelaunch                               MMAgent
Function        Disable-BC                                         BranchCache
Function        Disable-BCDowngrading                              BranchCache
Function        Disable-BCServeOnBattery                           BranchCache
Function        Disable-BitLocker                                  BitLocker
Function        Disable-BitLockerAutoUnlock                        BitLocker
Function        Disable-DAManualEntryPointSelection                DirectAccessClientComponents
Function        Disable-MMAgent                                    MMAgent
Function        Disable-NetAdapter                                 NetAdapter
Function        Disable-NetAdapterBinding                          NetAdapter
Function        Disable-NetAdapterChecksumOffload                  NetAdapter
Function        Disable-NetAdapterEncapsulatedPacketTaskOffload    NetAdapter
Function        Disable-NetAdapterIPsecOffload                     NetAdapter
Function        Disable-NetAdapterLso                              NetAdapter
Function        Disable-NetAdapterPowerManagement                  NetAdapter
Function        Disable-NetAdapterQos                              NetAdapter
Function        Disable-NetAdapterRdma                             NetAdapter
Function        Disable-NetAdapterRsc                              NetAdapter
Function        Disable-NetAdapterRss                              NetAdapter
Function        Disable-NetAdapterSriov                            NetAdapter
Function        Disable-NetAdapterVmq                              NetAdapter
Function        Disable-NetDnsTransitionConfiguration              NetworkTransition
Function        Disable-NetFirewallRule                            NetSecurity
Function        Disable-NetIPHttpsProfile                          NetworkTransition
Function        Disable-NetIPsecMainModeRule                       NetSecurity
Function        Disable-NetIPsecRule                               NetSecurity
Function        Disable-NetNatTransitionConfiguration              NetworkTransition
Function        Disable-OdbcPerfCounter                            Wdac
Function        Disable-PhysicalDiskIndication                     Storage
Function        Disable-PSTrace                                    PSDiagnostics
Function        Disable-PSWSManCombinedTrace                       PSDiagnostics
Function        Disable-ScheduledTask                              ScheduledTasks
Function        Disable-SmbDelegation                              SmbShare
Function        Disable-StorageEnclosureIdentification             Storage
Function        Disable-WdacBidTrace                               Wdac
Function        Disable-WSManTrace                                 PSDiagnostics
Function        Disconnect-IscsiTarget                             iSCSI
Function        Disconnect-VirtualDisk                             Storage
Function        Dismount-DiskImage                                 Storage
Function        E:
Function        Enable-BCDistributed                               BranchCache
Function        Enable-BCDowngrading                               BranchCache
Function        Enable-BCHostedClient                              BranchCache
Function        Enable-BCHostedServer                              BranchCache
Function        Enable-BCLocal                                     BranchCache
Function        Enable-BCServeOnBattery                            BranchCache
Function        Enable-BitLocker                                   BitLocker
Function        Enable-BitLockerAutoUnlock                         BitLocker
Function        Enable-DAManualEntryPointSelection                 DirectAccessClientComponents
Function        Enable-MMAgent                                     MMAgent
Function        Enable-NetAdapter                                  NetAdapter
Function        Enable-NetAdapterBinding                           NetAdapter
Function        Enable-NetAdapterChecksumOffload                   NetAdapter
Function        Enable-NetAdapterEncapsulatedPacketTaskOffload     NetAdapter
Function        Enable-NetAdapterIPsecOffload                      NetAdapter
Function        Enable-NetAdapterLso                               NetAdapter
Function        Enable-NetAdapterPowerManagement                   NetAdapter
Function        Enable-NetAdapterQos                               NetAdapter
Function        Enable-NetAdapterRdma                              NetAdapter
Function        Enable-NetAdapterRsc                               NetAdapter
Function        Enable-NetAdapterRss                               NetAdapter
Function        Enable-NetAdapterSriov                             NetAdapter
Function        Enable-NetAdapterVmq                               NetAdapter
Function        Enable-NetDnsTransitionConfiguration               NetworkTransition
Function        Enable-NetFirewallRule                             NetSecurity
Function        Enable-NetIPHttpsProfile                           NetworkTransition
Function        Enable-NetIPsecMainModeRule                        NetSecurity
Function        Enable-NetIPsecRule                                NetSecurity
Function        Enable-NetNatTransitionConfiguration               NetworkTransition
Function        Enable-OdbcPerfCounter                             Wdac
Function        Enable-PhysicalDiskIndication                      Storage
Function        Enable-PSTrace                                     PSDiagnostics
Function        Enable-PSWSManCombinedTrace                        PSDiagnostics
Function        Enable-ScheduledTask                               ScheduledTasks
Function        Enable-SmbDelegation                               SmbShare
Function        Enable-StorageEnclosureIdentification              Storage
Function        Enable-WdacBidTrace                                Wdac
Function        Enable-WSManTrace                                  PSDiagnostics
Function        Export-BCCachePackage                              BranchCache
Function        Export-BCSecretKey                                 BranchCache
Function        Export-ScheduledTask                               ScheduledTasks
Function        F:
Function        Find-NetIPsecRule                                  NetSecurity
Function        Find-NetRoute                                      NetTCPIP
Function        Format-Volume                                      Storage
Function        G:
Function        Get-AppBackgroundTask                              AppBackgroundTask
Function        Get-AppxLastError                                  Appx
Function        Get-AppxLog                                        Appx
Function        Get-AssignedAccess                                 AssignedAccess
Function        Get-BCClientConfiguration                          BranchCache
Function        Get-BCContentServerConfiguration                   BranchCache
Function        Get-BCDataCache                                    BranchCache
Function        Get-BCDataCacheExtension                           BranchCache
Function        Get-BCHashCache                                    BranchCache
Function        Get-BCHostedCacheServerConfiguration               BranchCache
Function        Get-BCNetworkConfiguration                         BranchCache
Function        Get-BCStatus                                       BranchCache
Function        Get-BitLockerVolume                                BitLocker
Function        Get-ClusteredScheduledTask                         ScheduledTasks
Function        Get-DAClientExperienceConfiguration                DirectAccessClientComponents
Function        Get-DAConnectionStatus                             NetworkConnectivityStatus
Function        Get-DAEntryPointTableItem                          DirectAccessClientComponents
Function        Get-Disk                                           Storage
Function        Get-DiskImage                                      Storage
Function        Get-DnsClient                                      DnsClient
Function        Get-DnsClientCache                                 DnsClient
Function        Get-DnsClientGlobalSetting                         DnsClient
Function        Get-DnsClientNrptGlobal                            DnsClient
Function        Get-DnsClientNrptPolicy                            DnsClient
Function        Get-DnsClientNrptRule                              DnsClient
Function        Get-DnsClientServerAddress                         DnsClient
Function        Get-DscConfiguration                               PSDesiredStateConfiguration
Function        Get-DscLocalConfigurationManager                   PSDesiredStateConfiguration
Function        Get-DscResource                                    PSDesiredStateConfiguration
Function        Get-Dtc                                            MsDtc
Function        Get-DtcAdvancedHostSetting                         MsDtc
Function        Get-DtcAdvancedSetting                             MsDtc
Function        Get-DtcClusterDefault                              MsDtc
Function        Get-DtcClusterTMMapping                            MsDtc
Function        Get-DtcDefault                                     MsDtc
Function        Get-DtcLog                                         MsDtc
Function        Get-DtcNetworkSetting                              MsDtc
Function        Get-DtcTransaction                                 MsDtc
Function        Get-DtcTransactionsStatistics                      MsDtc
Function        Get-DtcTransactionsTraceSession                    MsDtc
Function        Get-DtcTransactionsTraceSetting                    MsDtc
Function        Get-FileHash                                       Microsoft.PowerShell.Utility
Function        Get-FileIntegrity                                  Storage
Function        Get-FileStorageTier                                Storage
Function        Get-InitiatorId                                    Storage
Function        Get-InitiatorPort                                  Storage
Function        Get-IscsiConnection                                iSCSI
Function        Get-IscsiSession                                   iSCSI
Function        Get-IscsiTarget                                    iSCSI
Function        Get-IscsiTargetPortal                              iSCSI
Function        Get-IseSnippet                                     ISE
Function        Get-LogProperties                                  PSDiagnostics
Function        Get-MaskingSet                                     Storage
Function        Get-MMAgent                                        MMAgent
Function        Get-MpComputerStatus                               Defender
Function        Get-MpPreference                                   Defender
Function        Get-MpThreat                                       Defender
Function        Get-MpThreatCatalog                                Defender
Function        Get-MpThreatDetection                              Defender
Function        Get-NCSIPolicyConfiguration                        NetworkConnectivityStatus
Function        Get-Net6to4Configuration                           NetworkTransition
Function        Get-NetAdapter                                     NetAdapter
Function        Get-NetAdapterAdvancedProperty                     NetAdapter
Function        Get-NetAdapterBinding                              NetAdapter
Function        Get-NetAdapterChecksumOffload                      NetAdapter
Function        Get-NetAdapterEncapsulatedPacketTaskOffload        NetAdapter
Function        Get-NetAdapterHardwareInfo                         NetAdapter
Function        Get-NetAdapterIPsecOffload                         NetAdapter
Function        Get-NetAdapterLso                                  NetAdapter
Function        Get-NetAdapterPowerManagement                      NetAdapter
Function        Get-NetAdapterQos                                  NetAdapter
Function        Get-NetAdapterRdma                                 NetAdapter
Function        Get-NetAdapterRsc                                  NetAdapter
Function        Get-NetAdapterRss                                  NetAdapter
Function        Get-NetAdapterSriov                                NetAdapter
Function        Get-NetAdapterSriovVf                              NetAdapter
Function        Get-NetAdapterStatistics                           NetAdapter
Function        Get-NetAdapterVmq                                  NetAdapter
Function        Get-NetAdapterVMQQueue                             NetAdapter
Function        Get-NetAdapterVPort                                NetAdapter
Function        Get-NetCompartment                                 NetTCPIP
Function        Get-NetConnectionProfile                           NetConnection
Function        Get-NetDnsTransitionConfiguration                  NetworkTransition
Function        Get-NetDnsTransitionMonitoring                     NetworkTransition
Function        Get-NetEventNetworkAdapter                         NetEventPacketCapture
Function        Get-NetEventPacketCaptureProvider                  NetEventPacketCapture
Function        Get-NetEventProvider                               NetEventPacketCapture
Function        Get-NetEventSession                                NetEventPacketCapture
Function        Get-NetEventVmNetworkAdapter                       NetEventPacketCapture
Function        Get-NetEventVmSwitch                               NetEventPacketCapture
Function        Get-NetFirewallAddressFilter                       NetSecurity
Function        Get-NetFirewallApplicationFilter                   NetSecurity
Function        Get-NetFirewallInterfaceFilter                     NetSecurity
Function        Get-NetFirewallInterfaceTypeFilter                 NetSecurity
Function        Get-NetFirewallPortFilter                          NetSecurity
Function        Get-NetFirewallProfile                             NetSecurity
Function        Get-NetFirewallRule                                NetSecurity
Function        Get-NetFirewallSecurityFilter                      NetSecurity
Function        Get-NetFirewallServiceFilter                       NetSecurity
Function        Get-NetFirewallSetting                             NetSecurity
Function        Get-NetIPAddress                                   NetTCPIP
Function        Get-NetIPConfiguration                             NetTCPIP
Function        Get-NetIPHttpsConfiguration                        NetworkTransition
Function        Get-NetIPHttpsState                                NetworkTransition
Function        Get-NetIPInterface                                 NetTCPIP
Function        Get-NetIPsecDospSetting                            NetSecurity
Function        Get-NetIPsecMainModeCryptoSet                      NetSecurity
Function        Get-NetIPsecMainModeRule                           NetSecurity
Function        Get-NetIPsecMainModeSA                             NetSecurity
Function        Get-NetIPsecPhase1AuthSet                          NetSecurity
Function        Get-NetIPsecPhase2AuthSet                          NetSecurity
Function        Get-NetIPsecQuickModeCryptoSet                     NetSecurity
Function        Get-NetIPsecQuickModeSA                            NetSecurity
Function        Get-NetIPsecRule                                   NetSecurity
Function        Get-NetIPv4Protocol                                NetTCPIP
Function        Get-NetIPv6Protocol                                NetTCPIP
Function        Get-NetIsatapConfiguration                         NetworkTransition
Function        Get-NetLbfoTeam                                    NetLbfo
Function        Get-NetLbfoTeamMember                              NetLbfo
Function        Get-NetLbfoTeamNic                                 NetLbfo
Function        Get-NetNat                                         NetNat
Function        Get-NetNatExternalAddress                          NetNat
Function        Get-NetNatGlobal                                   NetNat
Function        Get-NetNatSession                                  NetNat
Function        Get-NetNatStaticMapping                            NetNat
Function        Get-NetNatTransitionConfiguration                  NetworkTransition
Function        Get-NetNatTransitionMonitoring                     NetworkTransition
Function        Get-NetNeighbor                                    NetTCPIP
Function        Get-NetOffloadGlobalSetting                        NetTCPIP
Function        Get-NetPrefixPolicy                                NetTCPIP
Function        Get-NetQosPolicy                                   NetQos
Function        Get-NetRoute                                       NetTCPIP
Function        Get-NetSwitchTeam                                  NetSwitchTeam
Function        Get-NetSwitchTeamMember                            NetSwitchTeam
Function        Get-NetTCPConnection                               NetTCPIP
Function        Get-NetTCPSetting                                  NetTCPIP
Function        Get-NetTeredoConfiguration                         NetworkTransition
Function        Get-NetTeredoState                                 NetworkTransition
Function        Get-NetTransportFilter                             NetTCPIP
Function        Get-NetUDPEndpoint                                 NetTCPIP
Function        Get-NetUDPSetting                                  NetTCPIP
Function        Get-OdbcDriver                                     Wdac
Function        Get-OdbcDsn                                        Wdac
Function        Get-OdbcPerfCounter                                Wdac
Function        Get-OffloadDataTransferSetting                     Storage
Function        Get-Partition                                      Storage
Function        Get-PartitionSupportedSize                         Storage
Function        Get-PcsvDevice                                     PcsvDevice
Function        Get-PhysicalDisk                                   Storage
Function        Get-PhysicalDiskStorageNodeView                    Storage
Function        Get-PrintConfiguration                             PrintManagement
Function        Get-Printer                                        PrintManagement
Function        Get-PrinterDriver                                  PrintManagement
Function        Get-PrinterPort                                    PrintManagement
Function        Get-PrinterProperty                                PrintManagement
Function        Get-PrintJob                                       PrintManagement
Function        Get-ResiliencySetting                              Storage
Function        Get-ScheduledTask                                  ScheduledTasks
Function        Get-ScheduledTaskInfo                              ScheduledTasks
Function        Get-SmbBandWidthLimit                              SmbShare
Function        Get-SmbClientConfiguration                         SmbShare
Function        Get-SmbClientNetworkInterface                      SmbShare
Function        Get-SmbConnection                                  SmbShare
Function        Get-SmbDelegation                                  SmbShare
Function        Get-SmbMapping                                     SmbShare
Function        Get-SmbMultichannelConnection                      SmbShare
Function        Get-SmbMultichannelConstraint                      SmbShare
Function        Get-SmbOpenFile                                    SmbShare
Function        Get-SmbServerConfiguration                         SmbShare
Function        Get-SmbServerNetworkInterface                      SmbShare
Function        Get-SmbSession                                     SmbShare
Function        Get-SmbShare                                       SmbShare
Function        Get-SmbShareAccess                                 SmbShare
Function        Get-SmbWitnessClient                               SmbWitness
Function        Get-StartApps                                      StartScreen
Function        Get-StorageDiagnosticInfo                          Storage
Function        Get-StorageEnclosure                               Storage
Function        Get-StorageEnclosureVendorData                     Storage
Function        Get-StorageJob                                     Storage
Function        Get-StorageNode                                    Storage
Function        Get-StoragePool                                    Storage
Function        Get-StorageProvider                                Storage
Function        Get-StorageReliabilityCounter                      Storage
Function        Get-StorageSetting                                 Storage
Function        Get-StorageSubSystem                               Storage
Function        Get-StorageTier                                    Storage
Function        Get-StorageTierSupportedSize                       Storage
Function        GetStreamHash                                      Microsoft.PowerShell.Utility
Function        Get-SupportedClusterSizes                          Storage
Function        Get-SupportedFileSystems                           Storage
Function        Get-TargetPort                                     Storage
Function        Get-TargetPortal                                   Storage
Function        Get-Verb
Function        Get-VirtualDisk                                    Storage
Function        Get-VirtualDiskSupportedSize                       Storage
Function        Get-Volume                                         Storage
Function        Get-VolumeCorruptionCount                          Storage
Function        Get-VolumeScrubPolicy                              Storage
Function        Get-VpnConnection                                  VpnClient
Function        Get-VpnConnectionTrigger                           VpnClient
Function        Get-WdacBidTrace                                   Wdac
Function        Get-WindowsDeveloperLicense                        WindowsDeveloperLicense
Function        Grant-SmbShareAccess                               SmbShare
Function        H:
Function        help
Function        Hide-VirtualDisk                                   Storage
Function        I:
Function        Import-BCCachePackage                              BranchCache
Function        Import-BCSecretKey                                 BranchCache
Function        Import-IseSnippet                                  ISE
Function        ImportSystemModules
Function        Initialize-Disk                                    Storage
Function        Install-Dtc                                        MsDtc
Function        Invoke-AsWorkflow                                  PSWorkflowUtility
Function        J:
Function        K:
Function        L:
Function        Lock-BitLocker                                     BitLocker
Function        M:
Function        mkdir
Function        more
Function        Mount-DiskImage                                    Storage
Function        Move-SmbWitnessClient                              SmbWitness
Function        N:
Function        New-DAEntryPointTableItem                          DirectAccessClientComponents
Function        New-DscCheckSum                                    PSDesiredStateConfiguration
Function        New-EapConfiguration                               VpnClient
Function        New-IscsiTargetPortal                              iSCSI
Function        New-IseSnippet                                     ISE
Function        New-MaskingSet                                     Storage
Function        New-NetAdapterAdvancedProperty                     NetAdapter
Function        New-NetEventSession                                NetEventPacketCapture
Function        New-NetFirewallRule                                NetSecurity
Function        New-NetIPAddress                                   NetTCPIP
Function        New-NetIPHttpsConfiguration                        NetworkTransition
Function        New-NetIPsecDospSetting                            NetSecurity
Function        New-NetIPsecMainModeCryptoSet                      NetSecurity
Function        New-NetIPsecMainModeRule                           NetSecurity
Function        New-NetIPsecPhase1AuthSet                          NetSecurity
Function        New-NetIPsecPhase2AuthSet                          NetSecurity
Function        New-NetIPsecQuickModeCryptoSet                     NetSecurity
Function        New-NetIPsecRule                                   NetSecurity
Function        New-NetLbfoTeam                                    NetLbfo
Function        New-NetNat                                         NetNat
Function        New-NetNatTransitionConfiguration                  NetworkTransition
Function        New-NetNeighbor                                    NetTCPIP
Function        New-NetQosPolicy                                   NetQos
Function        New-NetRoute                                       NetTCPIP
Function        New-NetSwitchTeam                                  NetSwitchTeam
Function        New-NetTransportFilter                             NetTCPIP
Function        New-Partition                                      Storage
Function        New-PSWorkflowSession                              PSWorkflow
Function        New-ScheduledTask                                  ScheduledTasks
Function        New-ScheduledTaskAction                            ScheduledTasks
Function        New-ScheduledTaskPrincipal                         ScheduledTasks
Function        New-ScheduledTaskSettingsSet                       ScheduledTasks
Function        New-ScheduledTaskTrigger                           ScheduledTasks
Function        New-SmbMapping                                     SmbShare
Function        New-SmbMultichannelConstraint                      SmbShare
Function        New-SmbShare                                       SmbShare
Function        New-StoragePool                                    Storage
Function        New-StorageSubsystemVirtualDisk                    Storage
Function        New-StorageTier                                    Storage
Function        New-VirtualDisk                                    Storage
Function        New-VirtualDiskClone                               Storage
Function        New-VirtualDiskSnapshot                            Storage
Function        New-Volume                                         Storage
Function        New-VpnServerAddress                               VpnClient
Function        O:
Function        Open-NetGPO                                        NetSecurity
Function        Optimize-Volume                                    Storage
Function        oss
Function        P:
Function        Pause
Function        prompt
Function        Publish-BCFileContent                              BranchCache
Function        Publish-BCWebContent                               BranchCache
Function        Q:
Function        R:
Function        Read-PrinterNfcTag                                 PrintManagement
Function        Register-ClusteredScheduledTask                    ScheduledTasks
Function        Register-DnsClient                                 DnsClient
Function        Register-IscsiSession                              iSCSI
Function        Register-ScheduledTask                             ScheduledTasks
Function        Register-StorageSubsystem                          Storage
Function        Remove-BCDataCacheExtension                        BranchCache
Function        Remove-BitLockerKeyProtector                       BitLocker
Function        Remove-DAEntryPointTableItem                       DirectAccessClientComponents
Function        Remove-DnsClientNrptRule                           DnsClient
Function        Remove-DscConfigurationDocument                    PSDesiredStateConfiguration
Function        Remove-DtcClusterTMMapping                         MsDtc
Function        Remove-InitiatorId                                 Storage
Function        Remove-InitiatorIdFromMaskingSet                   Storage
Function        Remove-IscsiTargetPortal                           iSCSI
Function        Remove-MaskingSet                                  Storage
Function        Remove-MpPreference                                Defender
Function        Remove-MpThreat                                    Defender
Function        Remove-NetAdapterAdvancedProperty                  NetAdapter
Function        Remove-NetEventNetworkAdapter                      NetEventPacketCapture
Function        Remove-NetEventPacketCaptureProvider               NetEventPacketCapture
Function        Remove-NetEventProvider                            NetEventPacketCapture
Function        Remove-NetEventSession                             NetEventPacketCapture
Function        Remove-NetEventVmNetworkAdapter                    NetEventPacketCapture
Function        Remove-NetEventVmSwitch                            NetEventPacketCapture
Function        Remove-NetFirewallRule                             NetSecurity
Function        Remove-NetIPAddress                                NetTCPIP
Function        Remove-NetIPHttpsCertBinding                       NetworkTransition
Function        Remove-NetIPHttpsConfiguration                     NetworkTransition
Function        Remove-NetIPsecDospSetting                         NetSecurity
Function        Remove-NetIPsecMainModeCryptoSet                   NetSecurity
Function        Remove-NetIPsecMainModeRule                        NetSecurity
Function        Remove-NetIPsecMainModeSA                          NetSecurity
Function        Remove-NetIPsecPhase1AuthSet                       NetSecurity
Function        Remove-NetIPsecPhase2AuthSet                       NetSecurity
Function        Remove-NetIPsecQuickModeCryptoSet                  NetSecurity
Function        Remove-NetIPsecQuickModeSA                         NetSecurity
Function        Remove-NetIPsecRule                                NetSecurity
Function        Remove-NetLbfoTeam                                 NetLbfo
Function        Remove-NetLbfoTeamMember                           NetLbfo
Function        Remove-NetLbfoTeamNic                              NetLbfo
Function        Remove-NetNat                                      NetNat
Function        Remove-NetNatExternalAddress                       NetNat
Function        Remove-NetNatStaticMapping                         NetNat
Function        Remove-NetNatTransitionConfiguration               NetworkTransition
Function        Remove-NetNeighbor                                 NetTCPIP
Function        Remove-NetQosPolicy                                NetQos
Function        Remove-NetRoute                                    NetTCPIP
Function        Remove-NetSwitchTeam                               NetSwitchTeam
Function        Remove-NetSwitchTeamMember                         NetSwitchTeam
Function        Remove-NetTransportFilter                          NetTCPIP
Function        Remove-OdbcDsn                                     Wdac
Function        Remove-Partition                                   Storage
Function        Remove-PartitionAccessPath                         Storage
Function        Remove-PhysicalDisk                                Storage
Function        Remove-Printer                                     PrintManagement
Function        Remove-PrinterDriver                               PrintManagement
Function        Remove-PrinterPort                                 PrintManagement
Function        Remove-PrintJob                                    PrintManagement
Function        Remove-SmbBandwidthLimit                           SmbShare
Function        Remove-SmbMapping                                  SmbShare
Function        Remove-SmbMultichannelConstraint                   SmbShare
Function        Remove-SmbShare                                    SmbShare
Function        Remove-StoragePool                                 Storage
Function        Remove-StorageTier                                 Storage
Function        Remove-TargetPortFromMaskingSet                    Storage
Function        Remove-VirtualDisk                                 Storage
Function        Remove-VirtualDiskFromMaskingSet                   Storage
Function        Remove-VpnConnection                               VpnClient
Function        Remove-VpnConnectionRoute                          VpnClient
Function        Remove-VpnConnectionTriggerApplication             VpnClient
Function        Remove-VpnConnectionTriggerDnsConfiguration        VpnClient
Function        Remove-VpnConnectionTriggerTrustedNetwork          VpnClient
Function        Rename-DAEntryPointTableItem                       DirectAccessClientComponents
Function        Rename-MaskingSet                                  Storage
Function        Rename-NetAdapter                                  NetAdapter
Function        Rename-NetFirewallRule                             NetSecurity
Function        Rename-NetIPHttpsConfiguration                     NetworkTransition
Function        Rename-NetIPsecMainModeCryptoSet                   NetSecurity
Function        Rename-NetIPsecMainModeRule                        NetSecurity
Function        Rename-NetIPsecPhase1AuthSet                       NetSecurity
Function        Rename-NetIPsecPhase2AuthSet                       NetSecurity
Function        Rename-NetIPsecQuickModeCryptoSet                  NetSecurity
Function        Rename-NetIPsecRule                                NetSecurity
Function        Rename-NetLbfoTeam                                 NetLbfo
Function        Rename-NetSwitchTeam                               NetSwitchTeam
Function        Rename-Printer                                     PrintManagement
Function        Repair-FileIntegrity                               Storage
Function        Repair-VirtualDisk                                 Storage
Function        Repair-Volume                                      Storage
Function        Reset-BC                                           BranchCache
Function        Reset-DAClientExperienceConfiguration              DirectAccessClientComponents
Function        Reset-DAEntryPointTableItem                        DirectAccessClientComponents
Function        Reset-DtcLog                                       MsDtc
Function        Reset-NCSIPolicyConfiguration                      NetworkConnectivityStatus
Function        Reset-Net6to4Configuration                         NetworkTransition
Function        Reset-NetAdapterAdvancedProperty                   NetAdapter
Function        Reset-NetDnsTransitionConfiguration                NetworkTransition
Function        Reset-NetIPHttpsConfiguration                      NetworkTransition
Function        Reset-NetIsatapConfiguration                       NetworkTransition
Function        Reset-NetTeredoConfiguration                       NetworkTransition
Function        Reset-PhysicalDisk                                 Storage
Function        Reset-StorageReliabilityCounter                    Storage
Function        Resize-Partition                                   Storage
Function        Resize-StorageTier                                 Storage
Function        Resize-VirtualDisk                                 Storage
Function        Restart-NetAdapter                                 NetAdapter
Function        Restart-PcsvDevice                                 PcsvDevice
Function        Restart-PrintJob                                   PrintManagement
Function        Restore-DscConfiguration                           PSDesiredStateConfiguration
Function        Resume-BitLocker                                   BitLocker
Function        Resume-PrintJob                                    PrintManagement
Function        Revoke-SmbShareAccess                              SmbShare
Function        S:
Function        Save-NetGPO                                        NetSecurity
Function        Set-AssignedAccess                                 AssignedAccess
Function        Set-BCAuthentication                               BranchCache
Function        Set-BCCache                                        BranchCache
Function        Set-BCDataCacheEntryMaxAge                         BranchCache
Function        Set-BCMinSMBLatency                                BranchCache
Function        Set-BCSecretKey                                    BranchCache
Function        Set-ClusteredScheduledTask                         ScheduledTasks
Function        Set-DAClientExperienceConfiguration                DirectAccessClientComponents
Function        Set-DAEntryPointTableItem                          DirectAccessClientComponents
Function        Set-Disk                                           Storage
Function        Set-DnsClient                                      DnsClient
Function        Set-DnsClientGlobalSetting                         DnsClient
Function        Set-DnsClientNrptGlobal                            DnsClient
Function        Set-DnsClientNrptRule                              DnsClient
Function        Set-DnsClientServerAddress                         DnsClient
Function        Set-DtcAdvancedHostSetting                         MsDtc
Function        Set-DtcAdvancedSetting                             MsDtc
Function        Set-DtcClusterDefault                              MsDtc
Function        Set-DtcClusterTMMapping                            MsDtc
Function        Set-DtcDefault                                     MsDtc
Function        Set-DtcLog                                         MsDtc
Function        Set-DtcNetworkSetting                              MsDtc
Function        Set-DtcTransaction                                 MsDtc
Function        Set-DtcTransactionsTraceSession                    MsDtc
Function        Set-DtcTransactionsTraceSetting                    MsDtc
Function        Set-FileIntegrity                                  Storage
Function        Set-FileStorageTier                                Storage
Function        Set-InitiatorPort                                  Storage
Function        Set-IscsiChapSecret                                iSCSI
Function        Set-LogProperties                                  PSDiagnostics
Function        Set-MMAgent                                        MMAgent
Function        Set-MpPreference                                   Defender
Function        Set-NCSIPolicyConfiguration                        NetworkConnectivityStatus
Function        Set-Net6to4Configuration                           NetworkTransition
Function        Set-NetAdapter                                     NetAdapter
Function        Set-NetAdapterAdvancedProperty                     NetAdapter
Function        Set-NetAdapterBinding                              NetAdapter
Function        Set-NetAdapterChecksumOffload                      NetAdapter
Function        Set-NetAdapterEncapsulatedPacketTaskOffload        NetAdapter
Function        Set-NetAdapterIPsecOffload                         NetAdapter
Function        Set-NetAdapterLso                                  NetAdapter
Function        Set-NetAdapterPowerManagement                      NetAdapter
Function        Set-NetAdapterQos                                  NetAdapter
Function        Set-NetAdapterRdma                                 NetAdapter
Function        Set-NetAdapterRsc                                  NetAdapter
Function        Set-NetAdapterRss                                  NetAdapter
Function        Set-NetAdapterSriov                                NetAdapter
Function        Set-NetAdapterVmq                                  NetAdapter
Function        Set-NetConnectionProfile                           NetConnection
Function        Set-NetDnsTransitionConfiguration                  NetworkTransition
Function        Set-NetEventPacketCaptureProvider                  NetEventPacketCapture
Function        Set-NetEventProvider                               NetEventPacketCapture
Function        Set-NetEventSession                                NetEventPacketCapture
Function        Set-NetFirewallAddressFilter                       NetSecurity
Function        Set-NetFirewallApplicationFilter                   NetSecurity
Function        Set-NetFirewallInterfaceFilter                     NetSecurity
Function        Set-NetFirewallInterfaceTypeFilter                 NetSecurity
Function        Set-NetFirewallPortFilter                          NetSecurity
Function        Set-NetFirewallProfile                             NetSecurity
Function        Set-NetFirewallRule                                NetSecurity
Function        Set-NetFirewallSecurityFilter                      NetSecurity
Function        Set-NetFirewallServiceFilter                       NetSecurity
Function        Set-NetFirewallSetting                             NetSecurity
Function        Set-NetIPAddress                                   NetTCPIP
Function        Set-NetIPHttpsConfiguration                        NetworkTransition
Function        Set-NetIPInterface                                 NetTCPIP
Function        Set-NetIPsecDospSetting                            NetSecurity
Function        Set-NetIPsecMainModeCryptoSet                      NetSecurity
Function        Set-NetIPsecMainModeRule                           NetSecurity
Function        Set-NetIPsecPhase1AuthSet                          NetSecurity
Function        Set-NetIPsecPhase2AuthSet                          NetSecurity
Function        Set-NetIPsecQuickModeCryptoSet                     NetSecurity
Function        Set-NetIPsecRule                                   NetSecurity
Function        Set-NetIPv4Protocol                                NetTCPIP
Function        Set-NetIPv6Protocol                                NetTCPIP
Function        Set-NetIsatapConfiguration                         NetworkTransition
Function        Set-NetLbfoTeam                                    NetLbfo
Function        Set-NetLbfoTeamMember                              NetLbfo
Function        Set-NetLbfoTeamNic                                 NetLbfo
Function        Set-NetNat                                         NetNat
Function        Set-NetNatGlobal                                   NetNat
Function        Set-NetNatTransitionConfiguration                  NetworkTransition
Function        Set-NetNeighbor                                    NetTCPIP
Function        Set-NetOffloadGlobalSetting                        NetTCPIP
Function        Set-NetQosPolicy                                   NetQos
Function        Set-NetRoute                                       NetTCPIP
Function        Set-NetTCPSetting                                  NetTCPIP
Function        Set-NetTeredoConfiguration                         NetworkTransition
Function        Set-NetUDPSetting                                  NetTCPIP
Function        Set-OdbcDriver                                     Wdac
Function        Set-OdbcDsn                                        Wdac
Function        Set-Partition                                      Storage
Function        Set-PcsvDeviceBootConfiguration                    PcsvDevice
Function        Set-PhysicalDisk                                   Storage
Function        Set-PrintConfiguration                             PrintManagement
Function        Set-Printer                                        PrintManagement
Function        Set-PrinterProperty                                PrintManagement
Function        Set-ResiliencySetting                              Storage
Function        Set-ScheduledTask                                  ScheduledTasks
Function        Set-SmbBandwidthLimit                              SmbShare
Function        Set-SmbClientConfiguration                         SmbShare
Function        Set-SmbPathAcl                                     SmbShare
Function        Set-SmbServerConfiguration                         SmbShare
Function        Set-SmbShare                                       SmbShare
Function        Set-StoragePool                                    Storage
Function        Set-StorageProvider                                Storage
Function        Set-StorageSetting                                 Storage
Function        Set-StorageSubSystem                               Storage
Function        Set-StorageTier                                    Storage
Function        Set-VirtualDisk                                    Storage
Function        Set-Volume                                         Storage
Function        Set-VolumeScrubPolicy                              Storage
Function        Set-VpnConnection                                  VpnClient
Function        Set-VpnConnectionIPsecConfiguration                VpnClient
Function        Set-VpnConnectionProxy                             VpnClient
Function        Set-VpnConnectionTriggerDnsConfiguration           VpnClient
Function        Set-VpnConnectionTriggerTrustedNetwork             VpnClient
Function        Show-NetFirewallRule                               NetSecurity
Function        Show-NetIPsecRule                                  NetSecurity
Function        Show-VirtualDisk                                   Storage
Function        Show-WindowsDeveloperLicenseRegistration           WindowsDeveloperLicense
Function        Start-AppBackgroundTask                            AppBackgroundTask
Function        Start-Dtc                                          MsDtc
Function        Start-DtcTransactionsTraceSession                  MsDtc
Function        Start-MpScan                                       Defender
Function        Start-MpWDOScan                                    Defender
Function        Start-NetEventSession                              NetEventPacketCapture
Function        Start-PcsvDevice                                   PcsvDevice
Function        Start-ScheduledTask                                ScheduledTasks
Function        Start-StorageDiagnosticLog                         Storage
Function        Start-Trace                                        PSDiagnostics
Function        Stop-DscConfiguration                              PSDesiredStateConfiguration
Function        Stop-Dtc                                           MsDtc
Function        Stop-DtcTransactionsTraceSession                   MsDtc
Function        Stop-NetEventSession                               NetEventPacketCapture
Function        Stop-PcsvDevice                                    PcsvDevice
Function        Stop-ScheduledTask                                 ScheduledTasks
Function        Stop-StorageDiagnosticLog                          Storage
Function        Stop-Trace                                         PSDiagnostics
Function        Suspend-BitLocker                                  BitLocker
Function        Suspend-PrintJob                                   PrintManagement
Function        Sync-NetIPsecRule                                  NetSecurity
Function        T:
Function        TabExpansion2
Function        Test-DscConfiguration                              PSDesiredStateConfiguration
Function        Test-Dtc                                           MsDtc
Function        Test-NetConnection                                 NetTCPIP
Function        U:
Function        Unblock-SmbShareAccess                             SmbShare
Function        Uninstall-Dtc                                      MsDtc
Function        Unlock-BitLocker                                   BitLocker
Function        Unregister-AppBackgroundTask                       AppBackgroundTask
Function        Unregister-ClusteredScheduledTask                  ScheduledTasks
Function        Unregister-IscsiSession                            iSCSI
Function        Unregister-ScheduledTask                           ScheduledTasks
Function        Unregister-StorageSubsystem                        Storage
Function        Unregister-WindowsDeveloperLicense                 WindowsDeveloperLicense
Function        Update-Disk                                        Storage
Function        Update-HostStorageCache                            Storage
Function        Update-IscsiTarget                                 iSCSI
Function        Update-IscsiTargetPortal                           iSCSI
Function        Update-MpSignature                                 Defender
Function        Update-NetIPsecRule                                NetSecurity
Function        Update-SmbMultichannelConnection                   SmbShare
Function        Update-StoragePool                                 Storage
Function        Update-StorageProviderCache                        Storage
Function        V:
Function        W:
Function        Write-DtcTransactionsTraceSession                  MsDtc
Function        Write-PrinterNfcTag                                PrintManagement
Function        Write-VolumeCache                                  Storage
Function        X:
Function        Y:
Function        Z:
Cmdlet          Add-AppxPackage                                    Appx
Cmdlet          Add-AppxProvisionedPackage                         Dism
Cmdlet          Add-BitsFile                                       BitsTransfer
Cmdlet          Add-CertificateEnrollmentPolicyServer              PKI
Cmdlet          Add-Computer                                       Microsoft.PowerShell.Manageme
Cmdlet          Add-Content                                        Microsoft.PowerShell.Manageme
Cmdlet          Add-History                                        Microsoft.PowerShell.Core
Cmdlet          Add-JobTrigger                                     PSScheduledJob
Cmdlet          Add-KdsRootKey                                     Kds
Cmdlet          Add-Member                                         Microsoft.PowerShell.Utility
Cmdlet          Add-PSSnapin                                       Microsoft.PowerShell.Core
Cmdlet          Add-Type                                           Microsoft.PowerShell.Utility
Cmdlet          Add-WindowsDriver                                  Dism
Cmdlet          Add-WindowsImage                                   Dism
Cmdlet          Add-WindowsPackage                                 Dism
Cmdlet          Checkpoint-Computer                                Microsoft.PowerShell.Manageme
Cmdlet          Clear-Content                                      Microsoft.PowerShell.Manageme
Cmdlet          Clear-EventLog                                     Microsoft.PowerShell.Manageme
Cmdlet          Clear-History                                      Microsoft.PowerShell.Core
Cmdlet          Clear-Item                                         Microsoft.PowerShell.Manageme
Cmdlet          Clear-ItemProperty                                 Microsoft.PowerShell.Manageme
Cmdlet          Clear-KdsCache                                     Kds
Cmdlet          Clear-Tpm                                          TrustedPlatformModule
Cmdlet          Clear-Variable                                     Microsoft.PowerShell.Utility
Cmdlet          Clear-WindowsCorruptMountPoint                     Dism
Cmdlet          Compare-Object                                     Microsoft.PowerShell.Utility
Cmdlet          Complete-BitsTransfer                              BitsTransfer
Cmdlet          Complete-DtcDiagnosticTransaction                  MsDtc
Cmdlet          Complete-Transaction                               Microsoft.PowerShell.Manageme
Cmdlet          Confirm-SecureBootUEFI                             SecureBoot
Cmdlet          Connect-PSSession                                  Microsoft.PowerShell.Core
Cmdlet          Connect-WSMan                                      Microsoft.WSMan.Management
Cmdlet          ConvertFrom-Csv                                    Microsoft.PowerShell.Utility
Cmdlet          ConvertFrom-Json                                   Microsoft.PowerShell.Utility
Cmdlet          ConvertFrom-SecureString                           Microsoft.PowerShell.Security
Cmdlet          ConvertFrom-StringData                             Microsoft.PowerShell.Utility
Cmdlet          Convert-Path                                       Microsoft.PowerShell.Manageme
Cmdlet          ConvertTo-Csv                                      Microsoft.PowerShell.Utility
Cmdlet          ConvertTo-Html                                     Microsoft.PowerShell.Utility
Cmdlet          ConvertTo-Json                                     Microsoft.PowerShell.Utility
Cmdlet          ConvertTo-SecureString                             Microsoft.PowerShell.Security
Cmdlet          ConvertTo-TpmOwnerAuth                             TrustedPlatformModule
Cmdlet          ConvertTo-Xml                                      Microsoft.PowerShell.Utility
Cmdlet          Copy-Item                                          Microsoft.PowerShell.Manageme
Cmdlet          Copy-ItemProperty                                  Microsoft.PowerShell.Manageme
Cmdlet          Debug-Process                                      Microsoft.PowerShell.Manageme
Cmdlet          Disable-AppBackgroundTaskDiagnosticLog             AppBackgroundTask
Cmdlet          Disable-ComputerRestore                            Microsoft.PowerShell.Manageme
Cmdlet          Disable-JobTrigger                                 PSScheduledJob
Cmdlet          Disable-PSBreakpoint                               Microsoft.PowerShell.Utility
Cmdlet          Disable-PSRemoting                                 Microsoft.PowerShell.Core
Cmdlet          Disable-PSSessionConfiguration                     Microsoft.PowerShell.Core
Cmdlet          Disable-ScheduledJob                               PSScheduledJob
Cmdlet          Disable-TlsSessionTicketKey                        TLS
Cmdlet          Disable-TpmAutoProvisioning                        TrustedPlatformModule
Cmdlet          Disable-WindowsErrorReporting                      WindowsErrorReporting
Cmdlet          Disable-WindowsOptionalFeature                     Dism
Cmdlet          Disable-WSManCredSSP                               Microsoft.WSMan.Management
Cmdlet          Disconnect-PSSession                               Microsoft.PowerShell.Core
Cmdlet          Disconnect-WSMan                                   Microsoft.WSMan.Management
Cmdlet          Dismount-WindowsImage                              Dism
Cmdlet          Enable-AppBackgroundTaskDiagnosticLog              AppBackgroundTask
Cmdlet          Enable-ComputerRestore                             Microsoft.PowerShell.Manageme
Cmdlet          Enable-JobTrigger                                  PSScheduledJob
Cmdlet          Enable-PSBreakpoint                                Microsoft.PowerShell.Utility
Cmdlet          Enable-PSRemoting                                  Microsoft.PowerShell.Core
Cmdlet          Enable-PSSessionConfiguration                      Microsoft.PowerShell.Core
Cmdlet          Enable-ScheduledJob                                PSScheduledJob
Cmdlet          Enable-TlsSessionTicketKey                         TLS
Cmdlet          Enable-TpmAutoProvisioning                         TrustedPlatformModule
Cmdlet          Enable-WindowsErrorReporting                       WindowsErrorReporting
Cmdlet          Enable-WindowsOptionalFeature                      Dism
Cmdlet          Enable-WSManCredSSP                                Microsoft.WSMan.Management
Cmdlet          Enter-PSSession                                    Microsoft.PowerShell.Core
Cmdlet          Exit-PSSession                                     Microsoft.PowerShell.Core
Cmdlet          Expand-WindowsImage                                Dism
Cmdlet          Export-Alias                                       Microsoft.PowerShell.Utility
Cmdlet          Export-BinaryMiLog                                 CimCmdlets
Cmdlet          Export-Certificate                                 PKI
Cmdlet          Export-Clixml                                      Microsoft.PowerShell.Utility
Cmdlet          Export-Console                                     Microsoft.PowerShell.Core
Cmdlet          Export-Counter                                     Microsoft.PowerShell.Diagnost
Cmdlet          Export-Csv                                         Microsoft.PowerShell.Utility
Cmdlet          Export-FormatData                                  Microsoft.PowerShell.Utility
Cmdlet          Export-ModuleMember                                Microsoft.PowerShell.Core
Cmdlet          Export-PfxCertificate                              PKI
Cmdlet          Export-PSSession                                   Microsoft.PowerShell.Utility
Cmdlet          Export-StartLayout                                 StartScreen
Cmdlet          Export-TlsSessionTicketKey                         TLS
Cmdlet          Export-WindowsDriver                               Dism
Cmdlet          Export-WindowsImage                                Dism
Cmdlet          ForEach-Object                                     Microsoft.PowerShell.Core
Cmdlet          Format-Custom                                      Microsoft.PowerShell.Utility
Cmdlet          Format-List                                        Microsoft.PowerShell.Utility
Cmdlet          Format-SecureBootUEFI                              SecureBoot
Cmdlet          Format-Table                                       Microsoft.PowerShell.Utility
Cmdlet          Format-Wide                                        Microsoft.PowerShell.Utility
Cmdlet          Get-Acl                                            Microsoft.PowerShell.Security
Cmdlet          Get-Alias                                          Microsoft.PowerShell.Utility
Cmdlet          Get-AppLockerFileInformation                       AppLocker
Cmdlet          Get-AppLockerPolicy                                AppLocker
Cmdlet          Get-AppxPackage                                    Appx
Cmdlet          Get-AppxPackageManifest                            Appx
Cmdlet          Get-AppxProvisionedPackage                         Dism
Cmdlet          Get-AuthenticodeSignature                          Microsoft.PowerShell.Security
Cmdlet          Get-BitsTransfer                                   BitsTransfer
Cmdlet          Get-Certificate                                    PKI
Cmdlet          Get-CertificateAutoEnrollmentPolicy                PKI
Cmdlet          Get-CertificateEnrollmentPolicyServer              PKI
Cmdlet          Get-CertificateNotificationTask                    PKI
Cmdlet          Get-ChildItem                                      Microsoft.PowerShell.Manageme
Cmdlet          Get-CimAssociatedInstance                          CimCmdlets
Cmdlet          Get-CimClass                                       CimCmdlets
Cmdlet          Get-CimInstance                                    CimCmdlets
Cmdlet          Get-CimSession                                     CimCmdlets
Cmdlet          Get-CmsMessage                                     Microsoft.PowerShell.Security
Cmdlet          Get-Command                                        Microsoft.PowerShell.Core
Cmdlet          Get-ComputerRestorePoint                           Microsoft.PowerShell.Manageme
Cmdlet          Get-Content                                        Microsoft.PowerShell.Manageme
Cmdlet          Get-ControlPanelItem                               Microsoft.PowerShell.Manageme
Cmdlet          Get-Counter                                        Microsoft.PowerShell.Diagnost
Cmdlet          Get-Credential                                     Microsoft.PowerShell.Security
Cmdlet          Get-Culture                                        Microsoft.PowerShell.Utility
Cmdlet          Get-DAPolicyChange                                 NetSecurity
Cmdlet          Get-Date                                           Microsoft.PowerShell.Utility
Cmdlet          Get-Event                                          Microsoft.PowerShell.Utility
Cmdlet          Get-EventLog                                       Microsoft.PowerShell.Manageme
Cmdlet          Get-EventSubscriber                                Microsoft.PowerShell.Utility
Cmdlet          Get-ExecutionPolicy                                Microsoft.PowerShell.Security
Cmdlet          Get-FormatData                                     Microsoft.PowerShell.Utility
Cmdlet          Get-Help                                           Microsoft.PowerShell.Core
Cmdlet          Get-History                                        Microsoft.PowerShell.Core
Cmdlet          Get-Host                                           Microsoft.PowerShell.Utility
Cmdlet          Get-HotFix                                         Microsoft.PowerShell.Manageme
Cmdlet          Get-Item                                           Microsoft.PowerShell.Manageme
Cmdlet          Get-ItemProperty                                   Microsoft.PowerShell.Manageme
Cmdlet          Get-Job                                            Microsoft.PowerShell.Core
Cmdlet          Get-JobTrigger                                     PSScheduledJob
Cmdlet          Get-KdsConfiguration                               Kds
Cmdlet          Get-KdsRootKey                                     Kds
Cmdlet          Get-Location                                       Microsoft.PowerShell.Manageme
Cmdlet          Get-Member                                         Microsoft.PowerShell.Utility
Cmdlet          Get-Module                                         Microsoft.PowerShell.Core
Cmdlet          Get-PfxCertificate                                 Microsoft.PowerShell.Security
Cmdlet          Get-PfxData                                        PKI
Cmdlet          Get-Process                                        Microsoft.PowerShell.Manageme
Cmdlet          Get-PSBreakpoint                                   Microsoft.PowerShell.Utility
Cmdlet          Get-PSCallStack                                    Microsoft.PowerShell.Utility
Cmdlet          Get-PSDrive                                        Microsoft.PowerShell.Manageme
Cmdlet          Get-PSProvider                                     Microsoft.PowerShell.Manageme
Cmdlet          Get-PSSession                                      Microsoft.PowerShell.Core
Cmdlet          Get-PSSessionConfiguration                         Microsoft.PowerShell.Core
Cmdlet          Get-PSSnapin                                       Microsoft.PowerShell.Core
Cmdlet          Get-Random                                         Microsoft.PowerShell.Utility
Cmdlet          Get-ScheduledJob                                   PSScheduledJob
Cmdlet          Get-ScheduledJobOption                             PSScheduledJob
Cmdlet          Get-SecureBootPolicy                               SecureBoot
Cmdlet          Get-SecureBootUEFI                                 SecureBoot
Cmdlet          Get-Service                                        Microsoft.PowerShell.Manageme
Cmdlet          Get-Tpm                                            TrustedPlatformModule
Cmdlet          Get-TpmEndorsementKeyInfo                          TrustedPlatformModule
Cmdlet          Get-TpmSupportedFeature                            TrustedPlatformModule
Cmdlet          Get-TraceSource                                    Microsoft.PowerShell.Utility
Cmdlet          Get-Transaction                                    Microsoft.PowerShell.Manageme
Cmdlet          Get-TroubleshootingPack                            TroubleshootingPack
Cmdlet          Get-TypeData                                       Microsoft.PowerShell.Utility
Cmdlet          Get-UICulture                                      Microsoft.PowerShell.Utility
Cmdlet          Get-Unique                                         Microsoft.PowerShell.Utility
Cmdlet          Get-Variable                                       Microsoft.PowerShell.Utility
Cmdlet          Get-WIMBootEntry                                   Dism
Cmdlet          Get-WinAcceptLanguageFromLanguageListOptOut        International
Cmdlet          Get-WinCultureFromLanguageListOptOut               International
Cmdlet          Get-WinDefaultInputMethodOverride                  International
Cmdlet          Get-WindowsDriver                                  Dism
Cmdlet          Get-WindowsEdition                                 Dism
Cmdlet          Get-WindowsErrorReporting                          WindowsErrorReporting
Cmdlet          Get-WindowsImage                                   Dism
Cmdlet          Get-WindowsImageContent                            Dism
Cmdlet          Get-WindowsOptionalFeature                         Dism
Cmdlet          Get-WindowsPackage                                 Dism
Cmdlet          Get-WindowsSearchSetting                           WindowsSearch
Cmdlet          Get-WinEvent                                       Microsoft.PowerShell.Diagnost
Cmdlet          Get-WinHomeLocation                                International
Cmdlet          Get-WinLanguageBarOption                           International
Cmdlet          Get-WinSystemLocale                                International
Cmdlet          Get-WinUILanguageOverride                          International
Cmdlet          Get-WinUserLanguageList                            International
Cmdlet          Get-WmiObject                                      Microsoft.PowerShell.Manageme
Cmdlet          Get-WSManCredSSP                                   Microsoft.WSMan.Management
Cmdlet          Get-WSManInstance                                  Microsoft.WSMan.Management
Cmdlet          Group-Object                                       Microsoft.PowerShell.Utility
Cmdlet          Import-Alias                                       Microsoft.PowerShell.Utility
Cmdlet          Import-BinaryMiLog                                 CimCmdlets
Cmdlet          Import-Certificate                                 PKI
Cmdlet          Import-Clixml                                      Microsoft.PowerShell.Utility
Cmdlet          Import-Counter                                     Microsoft.PowerShell.Diagnost
Cmdlet          Import-Csv                                         Microsoft.PowerShell.Utility
Cmdlet          Import-LocalizedData                               Microsoft.PowerShell.Utility
Cmdlet          Import-Module                                      Microsoft.PowerShell.Core
Cmdlet          Import-PfxCertificate                              PKI
Cmdlet          Import-PSSession                                   Microsoft.PowerShell.Utility
Cmdlet          Import-StartLayout                                 StartScreen
Cmdlet          Import-TpmOwnerAuth                                TrustedPlatformModule
Cmdlet          Initialize-Tpm                                     TrustedPlatformModule
Cmdlet          Invoke-CimMethod                                   CimCmdlets
Cmdlet          Invoke-Command                                     Microsoft.PowerShell.Core
Cmdlet          Invoke-Expression                                  Microsoft.PowerShell.Utility
Cmdlet          Invoke-History                                     Microsoft.PowerShell.Core
Cmdlet          Invoke-Item                                        Microsoft.PowerShell.Manageme
Cmdlet          Invoke-RestMethod                                  Microsoft.PowerShell.Utility
Cmdlet          Invoke-TroubleshootingPack                         TroubleshootingPack
Cmdlet          Invoke-WebRequest                                  Microsoft.PowerShell.Utility
Cmdlet          Invoke-WmiMethod                                   Microsoft.PowerShell.Manageme
Cmdlet          Invoke-WSManAction                                 Microsoft.WSMan.Management
Cmdlet          Join-DtcDiagnosticResourceManager                  MsDtc
Cmdlet          Join-Path                                          Microsoft.PowerShell.Manageme
Cmdlet          Limit-EventLog                                     Microsoft.PowerShell.Manageme
Cmdlet          Measure-Command                                    Microsoft.PowerShell.Utility
Cmdlet          Measure-Object                                     Microsoft.PowerShell.Utility
Cmdlet          Mount-WindowsImage                                 Dism
Cmdlet          Move-Item                                          Microsoft.PowerShell.Manageme
Cmdlet          Move-ItemProperty                                  Microsoft.PowerShell.Manageme
Cmdlet          New-Alias                                          Microsoft.PowerShell.Utility
Cmdlet          New-AppLockerPolicy                                AppLocker
Cmdlet          New-CertificateNotificationTask                    PKI
Cmdlet          New-CimInstance                                    CimCmdlets
Cmdlet          New-CimSession                                     CimCmdlets
Cmdlet          New-CimSessionOption                               CimCmdlets
Cmdlet          New-DtcDiagnosticTransaction                       MsDtc
Cmdlet          New-Event                                          Microsoft.PowerShell.Utility
Cmdlet          New-EventLog                                       Microsoft.PowerShell.Manageme
Cmdlet          New-Item                                           Microsoft.PowerShell.Manageme
Cmdlet          New-ItemProperty                                   Microsoft.PowerShell.Manageme
Cmdlet          New-JobTrigger                                     PSScheduledJob
Cmdlet          New-Module                                         Microsoft.PowerShell.Core
Cmdlet          New-ModuleManifest                                 Microsoft.PowerShell.Core
Cmdlet          New-NetIPsecAuthProposal                           NetSecurity
Cmdlet          New-NetIPsecMainModeCryptoProposal                 NetSecurity
Cmdlet          New-NetIPsecQuickModeCryptoProposal                NetSecurity
Cmdlet          New-Object                                         Microsoft.PowerShell.Utility
Cmdlet          New-PSDrive                                        Microsoft.PowerShell.Manageme
Cmdlet          New-PSSession                                      Microsoft.PowerShell.Core
Cmdlet          New-PSSessionConfigurationFile                     Microsoft.PowerShell.Core
Cmdlet          New-PSSessionOption                                Microsoft.PowerShell.Core
Cmdlet          New-PSTransportOption                              Microsoft.PowerShell.Core
Cmdlet          New-PSWorkflowExecutionOption                      PSWorkflow
Cmdlet          New-ScheduledJobOption                             PSScheduledJob
Cmdlet          New-SelfSignedCertificate                          PKI
Cmdlet          New-Service                                        Microsoft.PowerShell.Manageme
Cmdlet          New-TimeSpan                                       Microsoft.PowerShell.Utility
Cmdlet          New-TlsSessionTicketKey                            TLS
Cmdlet          New-Variable                                       Microsoft.PowerShell.Utility
Cmdlet          New-WebServiceProxy                                Microsoft.PowerShell.Manageme
Cmdlet          New-WindowsCustomImage                             Dism
Cmdlet          New-WindowsImage                                   Dism
Cmdlet          New-WinEvent                                       Microsoft.PowerShell.Diagnost
Cmdlet          New-WinUserLanguageList                            International
Cmdlet          New-WSManInstance                                  Microsoft.WSMan.Management
Cmdlet          New-WSManSessionOption                             Microsoft.WSMan.Management
Cmdlet          Optimize-WindowsImage                              Dism
Cmdlet          Out-Default                                        Microsoft.PowerShell.Core
Cmdlet          Out-File                                           Microsoft.PowerShell.Utility
Cmdlet          Out-GridView                                       Microsoft.PowerShell.Utility
Cmdlet          Out-Host                                           Microsoft.PowerShell.Core
Cmdlet          Out-Null                                           Microsoft.PowerShell.Core
Cmdlet          Out-Printer                                        Microsoft.PowerShell.Utility
Cmdlet          Out-String                                         Microsoft.PowerShell.Utility
Cmdlet          Pop-Location                                       Microsoft.PowerShell.Manageme
Cmdlet          Protect-CmsMessage                                 Microsoft.PowerShell.Security
Cmdlet          Push-Location                                      Microsoft.PowerShell.Manageme
Cmdlet          Read-Host                                          Microsoft.PowerShell.Utility
Cmdlet          Receive-DtcDiagnosticTransaction                   MsDtc
Cmdlet          Receive-Job                                        Microsoft.PowerShell.Core
Cmdlet          Receive-PSSession                                  Microsoft.PowerShell.Core
Cmdlet          Register-CimIndicationEvent                        CimCmdlets
Cmdlet          Register-EngineEvent                               Microsoft.PowerShell.Utility
Cmdlet          Register-ObjectEvent                               Microsoft.PowerShell.Utility
Cmdlet          Register-PSSessionConfiguration                    Microsoft.PowerShell.Core
Cmdlet          Register-ScheduledJob                              PSScheduledJob
Cmdlet          Register-WmiEvent                                  Microsoft.PowerShell.Manageme
Cmdlet          Remove-AppxPackage                                 Appx
Cmdlet          Remove-AppxProvisionedPackage                      Dism
Cmdlet          Remove-BitsTransfer                                BitsTransfer
Cmdlet          Remove-CertificateEnrollmentPolicyServer           PKI
Cmdlet          Remove-CertificateNotificationTask                 PKI
Cmdlet          Remove-CimInstance                                 CimCmdlets
Cmdlet          Remove-CimSession                                  CimCmdlets
Cmdlet          Remove-Computer                                    Microsoft.PowerShell.Manageme
Cmdlet          Remove-Event                                       Microsoft.PowerShell.Utility
Cmdlet          Remove-EventLog                                    Microsoft.PowerShell.Manageme
Cmdlet          Remove-Item                                        Microsoft.PowerShell.Manageme
Cmdlet          Remove-ItemProperty                                Microsoft.PowerShell.Manageme
Cmdlet          Remove-Job                                         Microsoft.PowerShell.Core
Cmdlet          Remove-JobTrigger                                  PSScheduledJob
Cmdlet          Remove-Module                                      Microsoft.PowerShell.Core
Cmdlet          Remove-PSBreakpoint                                Microsoft.PowerShell.Utility
Cmdlet          Remove-PSDrive                                     Microsoft.PowerShell.Manageme
Cmdlet          Remove-PSSession                                   Microsoft.PowerShell.Core
Cmdlet          Remove-PSSnapin                                    Microsoft.PowerShell.Core
Cmdlet          Remove-TypeData                                    Microsoft.PowerShell.Utility
Cmdlet          Remove-Variable                                    Microsoft.PowerShell.Utility
Cmdlet          Remove-WindowsDriver                               Dism
Cmdlet          Remove-WindowsImage                                Dism
Cmdlet          Remove-WindowsPackage                              Dism
Cmdlet          Remove-WmiObject                                   Microsoft.PowerShell.Manageme
Cmdlet          Remove-WSManInstance                               Microsoft.WSMan.Management
Cmdlet          Rename-Computer                                    Microsoft.PowerShell.Manageme
Cmdlet          Rename-Item                                        Microsoft.PowerShell.Manageme
Cmdlet          Rename-ItemProperty                                Microsoft.PowerShell.Manageme
Cmdlet          Repair-WindowsImage                                Dism
Cmdlet          Reset-ComputerMachinePassword                      Microsoft.PowerShell.Manageme
Cmdlet          Resolve-DnsName                                    DnsClient
Cmdlet          Resolve-Path                                       Microsoft.PowerShell.Manageme
Cmdlet          Restart-Computer                                   Microsoft.PowerShell.Manageme
Cmdlet          Restart-Service                                    Microsoft.PowerShell.Manageme
Cmdlet          Restore-Computer                                   Microsoft.PowerShell.Manageme
Cmdlet          Resume-BitsTransfer                                BitsTransfer
Cmdlet          Resume-Job                                         Microsoft.PowerShell.Core
Cmdlet          Resume-Service                                     Microsoft.PowerShell.Manageme
Cmdlet          Save-Help                                          Microsoft.PowerShell.Core
Cmdlet          Save-WindowsImage                                  Dism
Cmdlet          Select-Object                                      Microsoft.PowerShell.Utility
Cmdlet          Select-String                                      Microsoft.PowerShell.Utility
Cmdlet          Select-Xml                                         Microsoft.PowerShell.Utility
Cmdlet          Send-DtcDiagnosticTransaction                      MsDtc
Cmdlet          Send-MailMessage                                   Microsoft.PowerShell.Utility
Cmdlet          Set-Acl                                            Microsoft.PowerShell.Security
Cmdlet          Set-Alias                                          Microsoft.PowerShell.Utility
Cmdlet          Set-AppBackgroundTaskResourcePolicy                AppBackgroundTask
Cmdlet          Set-AppLockerPolicy                                AppLocker
Cmdlet          Set-AppXProvisionedDataFile                        Dism
Cmdlet          Set-AuthenticodeSignature                          Microsoft.PowerShell.Security
Cmdlet          Set-BitsTransfer                                   BitsTransfer
Cmdlet          Set-CertificateAutoEnrollmentPolicy                PKI
Cmdlet          Set-CimInstance                                    CimCmdlets
Cmdlet          Set-Content                                        Microsoft.PowerShell.Manageme
Cmdlet          Set-Culture                                        International
Cmdlet          Set-Date                                           Microsoft.PowerShell.Utility
Cmdlet          Set-DscLocalConfigurationManager                   PSDesiredStateConfiguration
Cmdlet          Set-ExecutionPolicy                                Microsoft.PowerShell.Security
Cmdlet          Set-Item                                           Microsoft.PowerShell.Manageme
Cmdlet          Set-ItemProperty                                   Microsoft.PowerShell.Manageme
Cmdlet          Set-JobTrigger                                     PSScheduledJob
Cmdlet          Set-KdsConfiguration                               Kds
Cmdlet          Set-Location                                       Microsoft.PowerShell.Manageme
Cmdlet          Set-PSBreakpoint                                   Microsoft.PowerShell.Utility
Cmdlet          Set-PSDebug                                        Microsoft.PowerShell.Core
Cmdlet          Set-PSSessionConfiguration                         Microsoft.PowerShell.Core
Cmdlet          Set-ScheduledJob                                   PSScheduledJob
Cmdlet          Set-ScheduledJobOption                             PSScheduledJob
Cmdlet          Set-SecureBootUEFI                                 SecureBoot
Cmdlet          Set-Service                                        Microsoft.PowerShell.Manageme
Cmdlet          Set-StrictMode                                     Microsoft.PowerShell.Core
Cmdlet          Set-TpmOwnerAuth                                   TrustedPlatformModule
Cmdlet          Set-TraceSource                                    Microsoft.PowerShell.Utility
Cmdlet          Set-Variable                                       Microsoft.PowerShell.Utility
Cmdlet          Set-WinAcceptLanguageFromLanguageListOptOut        International
Cmdlet          Set-WinCultureFromLanguageListOptOut               International
Cmdlet          Set-WinDefaultInputMethodOverride                  International
Cmdlet          Set-WindowsEdition                                 Dism
Cmdlet          Set-WindowsProductKey                              Dism
Cmdlet          Set-WindowsSearchSetting                           WindowsSearch
Cmdlet          Set-WinHomeLocation                                International
Cmdlet          Set-WinLanguageBarOption                           International
Cmdlet          Set-WinSystemLocale                                International
Cmdlet          Set-WinUILanguageOverride                          International
Cmdlet          Set-WinUserLanguageList                            International
Cmdlet          Set-WmiInstance                                    Microsoft.PowerShell.Manageme
Cmdlet          Set-WSManInstance                                  Microsoft.WSMan.Management
Cmdlet          Set-WSManQuickConfig                               Microsoft.WSMan.Management
Cmdlet          Show-Command                                       Microsoft.PowerShell.Utility
Cmdlet          Show-ControlPanelItem                              Microsoft.PowerShell.Manageme
Cmdlet          Show-EventLog                                      Microsoft.PowerShell.Manageme
Cmdlet          Sort-Object                                        Microsoft.PowerShell.Utility
Cmdlet          Split-Path                                         Microsoft.PowerShell.Manageme
Cmdlet          Split-WindowsImage                                 Dism
Cmdlet          Start-BitsTransfer                                 BitsTransfer
Cmdlet          Start-DscConfiguration                             PSDesiredStateConfiguration
Cmdlet          Start-DtcDiagnosticResourceManager                 MsDtc
Cmdlet          Start-Job                                          Microsoft.PowerShell.Core
Cmdlet          Start-Process                                      Microsoft.PowerShell.Manageme
Cmdlet          Start-Service                                      Microsoft.PowerShell.Manageme
Cmdlet          Start-Sleep                                        Microsoft.PowerShell.Utility
Cmdlet          Start-Transaction                                  Microsoft.PowerShell.Manageme
Cmdlet          Start-Transcript                                   Microsoft.PowerShell.Host
Cmdlet          Stop-Computer                                      Microsoft.PowerShell.Manageme
Cmdlet          Stop-DtcDiagnosticResourceManager                  MsDtc
Cmdlet          Stop-Job                                           Microsoft.PowerShell.Core
Cmdlet          Stop-Process                                       Microsoft.PowerShell.Manageme
Cmdlet          Stop-Service                                       Microsoft.PowerShell.Manageme
Cmdlet          Stop-Transcript                                    Microsoft.PowerShell.Host
Cmdlet          Suspend-BitsTransfer                               BitsTransfer
Cmdlet          Suspend-Job                                        Microsoft.PowerShell.Core
Cmdlet          Suspend-Service                                    Microsoft.PowerShell.Manageme
Cmdlet          Switch-Certificate                                 PKI
Cmdlet          Tee-Object                                         Microsoft.PowerShell.Utility
Cmdlet          Test-AppLockerPolicy                               AppLocker
Cmdlet          Test-Certificate                                   PKI
Cmdlet          Test-ComputerSecureChannel                         Microsoft.PowerShell.Manageme
Cmdlet          Test-Connection                                    Microsoft.PowerShell.Manageme
Cmdlet          Test-KdsRootKey                                    Kds
Cmdlet          Test-ModuleManifest                                Microsoft.PowerShell.Core
Cmdlet          Test-Path                                          Microsoft.PowerShell.Manageme
Cmdlet          Test-PSSessionConfigurationFile                    Microsoft.PowerShell.Core
Cmdlet          Test-WSMan                                         Microsoft.WSMan.Management
Cmdlet          Trace-Command                                      Microsoft.PowerShell.Utility
Cmdlet          Unblock-File                                       Microsoft.PowerShell.Utility
Cmdlet          Unblock-Tpm                                        TrustedPlatformModule
Cmdlet          Undo-DtcDiagnosticTransaction                      MsDtc
Cmdlet          Undo-Transaction                                   Microsoft.PowerShell.Manageme
Cmdlet          Unprotect-CmsMessage                               Microsoft.PowerShell.Security
Cmdlet          Unregister-Event                                   Microsoft.PowerShell.Utility
Cmdlet          Unregister-PSSessionConfiguration                  Microsoft.PowerShell.Core
Cmdlet          Unregister-ScheduledJob                            PSScheduledJob
Cmdlet          Update-DscConfiguration                            PSDesiredStateConfiguration
Cmdlet          Update-FormatData                                  Microsoft.PowerShell.Utility
Cmdlet          Update-Help                                        Microsoft.PowerShell.Core
Cmdlet          Update-List                                        Microsoft.PowerShell.Utility
Cmdlet          Update-TypeData                                    Microsoft.PowerShell.Utility
Cmdlet          Update-WIMBootEntry                                Dism
Cmdlet          Use-Transaction                                    Microsoft.PowerShell.Manageme
Cmdlet          Use-WindowsUnattend                                Dism
Cmdlet          Wait-Event                                         Microsoft.PowerShell.Utility
Cmdlet          Wait-Job                                           Microsoft.PowerShell.Core
Cmdlet          Wait-Process                                       Microsoft.PowerShell.Manageme
Cmdlet          Where-Object                                       Microsoft.PowerShell.Core
Cmdlet          Write-Debug                                        Microsoft.PowerShell.Utility
Cmdlet          Write-Error                                        Microsoft.PowerShell.Utility
Cmdlet          Write-EventLog                                     Microsoft.PowerShell.Manageme
Cmdlet          Write-Host                                         Microsoft.PowerShell.Utility
Cmdlet          Write-Output                                       Microsoft.PowerShell.Utility
Cmdlet          Write-Progress                                     Microsoft.PowerShell.Utility
Cmdlet          Write-Verbose                                      Microsoft.PowerShell.Utility
Cmdlet          Write-Warning                                      Microsoft.PowerShell.Utility